<?php
	
/**
 * Implements hook_services_resources().
 */
function mayurika_services_resources() {
	return array(
		'content-page' => array(
      'operations' => array(
        'index' => array(
          'help' => 'Get Content Page',
          'file' => array(
            'type' => 'inc',
            'module' => 'mayurika',
            'name' => 'include/mayurika',
          ),
          'callback' => 'inno_get_content_page',
          // 'args' => array(
          //   array(
          //     'name' => 'url',
          //     'type' => 'string',
          //     'description' => 'url of page',
          //     'source' => array('path' => 0),
          //     'optional' => TRUE,
          //   ),
          // ),
          'access callback' => 'inno_get_content_page_access',
          'access arguments append' => TRUE,
        ),
      ),
    ),
    'saree' => array(
      'operations' => array(
        'index' => array(
          'help' => 'Get Content Page',
          'file' => array(
            'type' => 'inc',
            'module' => 'mayurika',
            'name' => 'include/mayurika',
          ),
          'callback' => 'mayurika_get_saree',
          'access callback' => 'mayurika_get_saree_access',
          'access arguments append' => TRUE,
        ),
      ),
    ),
    'kurti' => array(
      'operations' => array(
        'index' => array(
          'help' => 'Get All kurties',
          'file' => array(
            'type' => 'inc',
            'module' => 'mayurika',
            'name' => 'include/mayurika',
          ),
          'callback' => 'mayurika_get_kurti',
          'access callback' => 'mayurika_get_kurti_access',
          'access arguments append' => TRUE,
        ),
      ),
    ),
    'lehenga' => array(
      'operations' => array(
        'index' => array(
          'help' => 'Get All lehenga',
          'file' => array(
            'type' => 'inc',
            'module' => 'mayurika',
            'name' => 'include/mayurika',
          ),
          'callback' => 'mayurika_get_lehenga',
          'access callback' => 'mayurika_get_lehenga_access',
          'access arguments append' => TRUE,
        ),
      ),
    ),
    'banner' => array(
      'operations' => array(
        'index' => array(
          'help' => 'Get All banner',
          'file' => array(
            'type' => 'inc',
            'module' => 'mayurika',
            'name' => 'include/mayurika',
          ),
          'callback' => 'mayurika_get_banner',
          'access callback' => 'mayurika_get_banner_access',
          'access arguments append' => TRUE,
        ),
      ),
    ),
	);
}